name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP and Set Password
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user Administrator User#123456 /add
          net localgroup Administrators Administrator /add
      - name: Start Pinggy TCP Tunnel
        run: |
          # Téléchargement et installation d'un client SSH portable ou utilisation directe de ssh
          # On lance le tunnel TCP vers le port 3389
          ssh -o StrictHostKeyChecking=no -p 443 -R 0:localhost:3389 tcp.pinggy.io
      - name: Keep Alive
        run: Start-Sleep -Seconds 21600
