name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP and Set Password
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user Administrator User#123456 /add
          net localgroup Administrators Administrator /add
      - name: Install Node.js and LocalTunnel
        run: |
          npm install -g localtunnel
      - name: Start LocalTunnel (TCP/RDP)
        run: |
          # Démarrage de localtunnel sur le port 3389
          lt --port 3389
      - name: Keep Alive
        run: Start-Sleep -Seconds 21600
